name: Tag, Build, and Push Image

on:
  push:
    branches:
    - master
    paths-ignore:
    - 'README.md'
    - '.github/**'
    
env:
  SERVICE_NAME: cancerdata
  GOOGLE_PROJECT: broad-dsp-gcr-public
jobs:
  tag-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current code
      uses: actions/checkout@master
    - name: Bump version and push tag
      id: tag
      uses: databiosphere/github-actions/actions/bumper@bumper-0.0.6
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
        RELEASE_BRANCHES: master
        WITH_V: true
        
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.GCR_PUBLISH_KEY_B64 }}

    - name: Explicitly auth Docker for GCR
      run: gcloud auth configure-docker --quiet

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build and push GCR image using Jib
      run: "./gradlew jib --image=gcr.io/${GOOGLE_PROJECT}/${SERVICE_NAME}:${{ steps.tag.outputs.tag }}"
      env:
        SERVICE_VERSION: ${{ steps.tag.outputs.tag }}

    - name: Deploy to Terra Dev environment
      if: github.event_name == 'push'
      uses: broadinstitute/repository-dispatch@master
      with:
        token: ${{ secrets.BROADBOT_TOKEN }}
        repository: broadinstitute/terra-helmfile
        event-type: update-service
        client-payload: '{"service": "cancerdata", "version": "${{ steps.tag.outputs.tag }}"}'
