name: Tests

on: [push]

jobs:
  gradletest:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
        #   DATABASE_USER: manager 
        #   DATABASE_PASSWORD: password 
        #   DATABASE_NAME: cda
        #   POSTGRES_DB: postgres
        #   POSTGRES_PASSWORD: postgres
        #   POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 60s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8.0
      uses: actions/setup-java@v1
      with:
        java-version: 8.0
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: |
        psql postgres -c "create user manager password 'password';"
        psql postgres -c "create database cda with owner = manager;"
        ./gradlew build
    - name: Run test
      run: |
        ./gradlew test
    - name: Run check
      run: ./gradlew check
