name: Tests

on: [push]

jobs:
  gradletest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8.0
      uses: actions/setup-java@v1
      with:
        java-version: 8.0
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: |
        service postgresql start
        psql postgres -c "create user manager password 'password';"
        psql postgres -c "create database cda with owner = manager;"
        ./gradlew build
    - name: Run test
      run: |
        ./gradlew test
    - name: Run check
      run: ./gradlew check
