name: Tests

on: [push]

jobs:
  gradletest:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        # env:
        #   POSTGRES_DB: postgres        
        #   POSTGRES_PASSWORD: postgres
        #   POSTGRES_USER: postgres
        # ports:
        #   - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8.0
      uses: actions/setup-java@v1
      with:
        java-version: 8.0
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build
    - name: Run test
      run: |
        psql postgres -c "create user manager password 'password';"
        psql postgres -c "create database cda with owner = manager;"

        ./gradlew test
    - name: Run check
      run: ./gradlew check
